// <auto-generated />
namespace ARMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedteacherbtaddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedteacherbtaddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201912071623541_added-teacher-bt-address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
