// <auto-generated />
namespace ARMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class removenotneededidfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removenotneededidfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201911161747202_remove-not-needed-id-fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
